### ISSUE TITLE
File Duplication when renaming

### ISSUE THREAD

**Issue by Freshou** [arawa/workspace#916] opened 2024-02-23 13:49 UTC
WorkSpace 2.0.4
NextCloud 26.0.11 (But also tested on a NextCloud 27.1.6)
Client macOS

When renaming a file in a WorkSpace Folder, 8 time out of 10, the file is renamed but the server throw out en error "move to invalid location, restoring previous file" 
but both files are now on the server... 

If I try the same thing on a NextCloud Standard shared folder, that do not happen...

**Comment by Freshou** [comment] 2024-03-01 17:12
Any news here ????

**Comment by Freshou** [comment] 2024-03-04 20:50
UN peu plus de détail concernant le problème avec WorkSpace... 
Dans un dossier partagé depuis WorkSpace, si j'ai un fichier, que je demande de dupliquer, il me créé "mon beau fichier copie.bla" ... Si je renommes le fichier créé par la duplication, alors je me retrouves avec une 2e copie du fichier en question que le client NextCloud me ramène localement

**Comment by zak39** [comment] 2024-03-05 14:20
Hi @Freshou :wave: 

Thanks for your issue :+1: 

Workspace is based on Groupfolders and the problem you describe is with Groupfodlers.

We will look at this problem.

**Comment by Freshou** [comment] 2024-03-05 17:17
Just did some update today (bug still here) ... 

Current NextCloud Version : 27.1.7
Group folders : 15.3.5
WorkSpace 3.0.5

running under apache and php-fpm8.1

**Comment by Freshou** [comment] 2024-03-05 17:22
All currently active APP on that NextCloud 

  - activity: 2.19.0
  - admin_audit: 1.17.0
  - announcementcenter: 6.7.0
  - appointments: 2.0.0
  - bruteforcesettings: 2.7.0
  - calendar: 4.6.6
  - calendar_resource_management: 0.6.0
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - collectives: 2.9.2
  - comments: 1.17.0
  - contacts: 5.5.2
  - contactsinteraction: 1.8.0
  - csp_editor: 1.3.1
  - dashboard: 7.7.0
  - dav: 1.27.0
  - deck: 1.11.4
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_accesscontrol: 1.17.1
  - files_antivirus: 5.4.2
  - files_external: 1.19.0
  - files_fulltextsearch: 27.0.1
  - files_fulltextsearch_tesseract: 27.0.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - forms: 3.4.6
  - fulltextsearch: 27.0.3
  - fulltextsearch_elasticsearch: 27.0.5
  - groupfolders: 15.3.5
  - imageconverter: 1.3.5
  - impersonate: 1.14.0
  - integration_ews: 1.0.37
  - integration_gptzero: 0.1.5
  - integration_openai: 1.1.5
  - integration_slack: 1.0.1
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - mail: 3.5.7
  - nextcloud_announcements: 1.16.0
  - notifications: 2.15.0
  - oauth2: 1.15.2
  - password_policy: 1.17.0
  - passwords: 2023.12.32
  - photos: 2.3.0
  - polls: 5.4.3
  - previewgenerator: 5.4.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - related_resources: 1.2.0
  - richdocuments: 8.2.5
  - richdocumentscode: 23.5.705
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - spreed: 17.1.6
  - support: 1.10.0
  - survey_client: 1.15.0
  - systemtags: 1.17.0
  - tables: 0.6.6
  - tasks: 0.15.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_admin: 4.4.0
  - twofactor_backupcodes: 1.16.0
  - twofactor_email: 2.7.4
  - twofactor_nextcloud_notification: 3.8.0
  - twofactor_totp: 9.0.0
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
  - workspace: 3.0.5

**Comment by zak39** [comment] 2024-03-05 21:00
Okay, if I understand, you use PHP8.1, right ?

**Comment by Freshou** [comment] 2024-03-05 21:01
Yes, php 8.1

**Comment by zak39** [comment] 2024-03-06 11:07
It's very strange... I tried several times with a csv and jpg file. And I didn't get a duplicate file

My steps :

- Create a workspace
- Go to the workspace/groupfolders
- Drag and Drop a csv and jpg file
- Renamed both files several times

**Comment by Freshou** [comment] 2024-03-06 14:06
No... 

You have to sync the WorkSpace/Group folder with the NextCloud Client... 
In the sync folder:
add a file, wait for it to be sync
duplicate the file, wait for it to be sync
rename de duplicate file, wait for it to be sync
few second later, another sync will happen and you will have the duplicate file AND the renamed duplicate file

I'm on a Mac... I don't know if the way the Mac duplicate file can have an incidence on the way it's sync ...

**Comment by Freshou** [comment] 2024-03-18 18:47
Any news here ?

**Comment by zak39** [comment] 2024-03-19 11:02
Hi @Freshou,

I could reproduce the bug with success. But, I don't yet know if it's Groupfolders or Files that's causing the bug

**Comment by Freshou** [comment] 2024-03-19 11:06
Outside of a group foldet, it doesn’t duplicate…

but i haven’t tried in a group folder that is not created by workspace

**Comment by ThibautPlg** [comment] 2024-08-26 12:34
See https://github.com/nextcloud/groupfolders/issues/3041
looks like a desktop/server related issue. Closing this issue for now.

**Closed by ThibautPlg** 2024-08-26 12:34 UTC
